# Generated by Django 3.2.12 on 2022-02-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_description_place_descriptio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='descriptio',
            new_name='description',
        ),
    ]
