# Generated by Django 3.2.12 on 2022-02-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='gfgfdg', upload_to='galary'),
            preserve_default=False,
        ),
    ]
