# Generated by Django 3.2.12 on 2022-02-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='movie',
            name='image2',
            field=models.ImageField(default=1, upload_to='galary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='image3',
            field=models.ImageField(default='2', upload_to='galary'),
            preserve_default=False,
        ),
    ]
