# Generated by Django 3.2.12 on 2022-03-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image1',
            field=models.ImageField(blank=True, upload_to='galary'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image2',
            field=models.ImageField(blank=True, upload_to='galary'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image3',
            field=models.ImageField(blank=True, upload_to='galary'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
