# Generated by Django 3.2.12 on 2022-03-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_auto_20220317_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image1',
            field=models.ImageField(upload_to='galary'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image2',
            field=models.ImageField(upload_to='galary'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image3',
            field=models.ImageField(upload_to='galary'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
    ]
